INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1034', 'Top Loading Nintendo NES Console', 'Nintendo', 'Consoles', 'Like New',  88.85, 'Sold');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1044', 'Mega Man 64', '', 'Games', 'Fair',  221.43, 'Sold');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1028', 'Legend of Zelda', 'Nintendo', 'Games', 'Near Mint',  16.46, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1023', 'Teenage Mutant Ninja Turtles Hyperstone Heist', '', 'Games', 'Near Mint',  280.94, 'Sold');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1015', 'Batman The Video Game', '', 'Games', 'Near Mint',  349.38, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1038', 'Little Samson', '', 'Games', 'Excellent',  18.54, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1021', 'Bomberman 64 Second Attack', '', 'Games', 'Like New',  180.82, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1044', 'Zelda II The Adventure of Link', 'Nintendo', 'Games', 'Excellent',  272.06, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1042', 'Mario Kart 64', 'Nintendo', 'Games', 'Good',  277.35, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1011', 'Mortal Kombat', '', 'Games', 'Near Mint',  171.27, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1044', 'Ogre Battle 64: Person of Lordly Caliber', '', 'Games', 'Good',  180.87, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1038', 'Sonic & Knuckles', 'Sega', 'Games', 'Some Wear and Tear',  18.96, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1005', 'Teenage Mutant Ninja Turtles II [No Free Pizza Offer]', '', 'Games', 'Near Mint',  82.18, 'Sold');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1020', 'Golden Axe', '', 'Games', 'Good',  311.55, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1036', 'Bomberman 64 Second Attack', '', 'Games', 'Good',  56.31, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1020', 'Altered Beast', '', 'Games', 'Used',  198.93, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1019', 'Earthworm Jim', '', 'Games', 'Some Wear and Tear',  36.38, 'Sold');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1027', 'Turok 2 Seeds of Evil', '', 'Games', 'Some Wear and Tear',  88.13, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1018', 'Golden Axe', '', 'Games', 'Like New',  229.92, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1008', 'Streets of Rage 3', '', 'Games', 'Fair',  319.66, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1005', 'Mike Tyson''s Punch-Out', '', 'Games', 'Excellent',  294.88, 'Sold');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1012', 'Mario Kart 64', 'Nintendo', 'Games', 'Some Wear and Tear',  218.52, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1042', 'Family Fun Fitness Stadium Events', '', 'Games', 'Excellent',  197.11, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1011', 'NBA Jam', '', 'Games', 'Some Wear and Tear',  129.52, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1042', 'Ninja Gaiden III Ancient Ship of Doom', '', 'Games', 'Like New',  120.39, 'Sold');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1039', 'WWF No Mercy', '', 'Games', 'Near Mint',  10.74, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1007', 'Funtastic Grape Purple Nintendo 64 System', 'Nintendo', 'Consoles', 'Good',  116.69, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1037', 'Super Mario Bros and Duck Hunt', 'Nintendo', 'Games', 'Excellent',  280.59, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1033', 'Castlevania III Dracula''s Curse', '', 'Games', 'Some Wear and Tear',  217.98, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1035', 'Pikachu Nintendo 64 System', 'Nintendo', 'Consoles', 'Near Mint',  15.03, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1007', 'Teenage Mutant Ninja Turtles', '', 'Games', 'Some Wear and Tear',  149.24, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1022', 'WWF No Mercy', '', 'Games', 'Fair',  183.99, 'Sold');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1039', 'Final Fantasy', '', 'Games', 'Good',  170.74, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1044', 'Golden Axe', '', 'Games', 'Fair',  209.44, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1035', 'Super C', '', 'Games', 'Used',  99.06, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1030', 'Funtastic Jungle Green Nintendo 64 System', '', 'Consoles', 'Near Mint',  107.77, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1042', 'Banjo-Kazooie', '', 'Games', 'Like New',  315.90, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1036', 'Aladdin', '', 'Games', 'Good',  238.46, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1012', 'MUSHA', '', 'Games', 'Good',  275.68, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1021', 'Castlevania: Bloodlines', '', 'Games', 'Near Mint',  269.74, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1041', 'Paper Mario', 'Nintendo', 'Games', 'Excellent',  311.22, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1018', 'Nintendo NES Action Set Console', '', 'Consoles', 'Fair',  204.14, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1030', 'Ogre Battle 64: Person of Lordly Caliber', '', 'Games', 'Excellent',  201.25, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1024', 'NBA Jam', '', 'Games', 'Fair',  298.75, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1031', 'Earthworm Jim', '', 'Games', 'Near Mint',  261.86, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1005', 'Castlevania', '', 'Games', 'Near Mint',  168.86, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1036', 'Sega Genesis Mini 2', 'Sega', 'Games', 'Like New',  292.61, 'Sold');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1039', 'Funtastic Grape Purple Nintendo 64 System', '', 'Consoles', 'Excellent',  96.75, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1011', 'Legend of Zelda', 'Nintendo', 'Games', 'Used',  159.32, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1041', 'Funtastic Grape Purple Nintendo 64 System', 'Nintendo', 'Consoles', 'Some Wear and Tear',  14.14, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1039', 'Perfect Dark', '', 'Games', 'Good',  343.28, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1026', 'Funtastic Jungle Green Nintendo 64 System', 'Nintendo', 'Consoles', 'Fair',  325.61, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1043', 'X-Men', '', 'Games', 'Excellent',  43.34, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1045', 'Stunt Racer', '', 'Games', 'Some Wear and Tear',  185.54, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1033', 'Mortal Kombat 3', 'Playstation', 'Games', 'Used',  187.32, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1012', 'Clay Fighter Sculptors Cut', '', 'Games', 'Used',  41.72, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1032', 'Splatterhouse 3', '', 'Games', 'Used',  149.37, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1044', 'Zelda Majora''s Mask', 'Nintendo', 'Games', 'Near Mint',  166.82, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1039', 'Zelda II The Adventure of Link', 'Nintendo', 'Games', 'Near Mint',  194.83, 'Sold');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1044', 'Metroid', '', 'Games', 'Some Wear and Tear',  147.14, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1009', 'Eternal Champions', '', 'Games', 'Fair',  210.69, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1012', 'Rocket Knight Adventures', '', 'Games', 'Fair',  244.07, 'Sold');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1001', 'Power Blade 2', '', 'Games', 'Fair',  173.62, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1025', 'Zelda II The Adventure of Link', 'Nintendo', 'Games', 'Some Wear and Tear',  86.68, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1044', 'Splatterhouse 2', '', 'Games', 'Good',  205.69, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1037', 'Super Mario 64', 'Nintendo', 'Games', 'Fair',  162.67, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1007', 'Kirby 64: The Crystal Shards', '', 'Games', 'Fair',  215.90, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1014', 'Mortal Kombat 3', '', 'Games', 'Used',  212.00, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1035', 'Pokemon Stadium 2', '', 'Games', 'Excellent',  134.22, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1027', 'Crusader of Centy', '', 'Games', 'Excellent',  52.22, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1033', 'Zelda Majora''s Mask [Not for Resale Gray]', 'Nintendo', 'Games', 'Good',  263.18, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1012', 'Teenage Mutant Ninja Turtles III The Manhattan Project', '', 'Games', 'Excellent',  39.90, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1041', 'Sonic the Hedgehog 2 [Not for Resale]', 'Sega', 'Games', 'Near Mint',  122.45, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1045', 'Mega Man', '', 'Games', 'Like New',  197.61, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1018', 'Dr. Mario', 'Nintendo', 'Games', 'Near Mint',  224.39, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1037', 'Mega Man', '', 'Games', 'Fair',  151.55, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1021', 'Gunstar Heroes', '', 'Games', 'Like New',  21.04, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1020', 'Sonic the Hedgehog [Not for Resale]', 'Sega', 'Games', 'Used',  155.40, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1040', 'Little Samson', '', 'Games', 'Used',  195.50, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1027', 'Duck Tales 2', '', 'Games', 'Used',  341.64, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1014', 'Teenage Mutant Ninja Turtles III The Manhattan Project', '', 'Games', 'Good',  209.30, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1021', 'Ms. Pac-Man', '', 'Games', 'Used',  270.38, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1037', 'Tetris', '', 'Games', 'Some Wear and Tear',  10.62, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1005', 'Top Loading Nintendo NES Console', '', 'Consoles', 'Some Wear and Tear',  342.06, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1045', 'Sega Genesis CDx Console', '', 'Consoles', 'Excellent',  188.96, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1040', 'Mario Bros', '', 'Games', 'Near Mint',  221.98, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1004', 'Ninja Gaiden III Ancient Ship of Doom', '', 'Games', 'Excellent',  309.02, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1000', 'Mega Man 6', '', 'Games', 'Excellent',  143.57, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1015', 'Battletoads', '', 'Games', 'Fair',  43.57, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1038', 'Worms Armageddon', '', 'Games', 'Some Wear and Tear',  310.67, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1002', 'Stunt Racer', '', 'Games', 'Some Wear and Tear',  222.46, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1045', 'Sonic the Hedgehog 2', '', 'Games', 'Fair',  156.97, 'Sold');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1024', 'Mike Tyson''s Punch-Out [5 Screw]', '', 'Games', 'Used',  328.18, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1024', 'Mega Man 5', '', 'Games', 'Good',  244.71, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1029', 'Mario Party 3', 'Nintendo', 'Games', 'Excellent',  260.63, 'Sold');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1006', 'Family Fun Fitness Stadium Events', '', 'Games', 'Used',  314.84, 'Sold');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1013', 'Family Fun Fitness Stadium Events', '', 'Games', 'Near Mint',  295.19, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1041', 'MUSHA', '', 'Games', 'Near Mint',  40.70, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1018', 'Dr. Mario', 'Nintendo', 'Games', 'Fair',  313.64, 'Available');
INSERT INTO ITEM (ItemID, SellerID, ItemName, Brand, Category, State, Price, Status) VALUES (NULL, '1018', 'Bomberman 64 Second Attack', '', 'Games', 'Like New',  245.78, 'Available');